name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
        type: string
      developementVersion:
        description: 'Developement Version'
        required: true
        type: string
        default: '-SNAPSHOT'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        server-id: ossrh-releases-pendula95 # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_CENTRAL_USERNAME # env variable for username in deploy
        server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
    
    - name: Configure git user
      run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      
    - name: Release
      id: releas
      run:  mvn -B release:prepare release:perform -Dresume=false -DskipTests=true -Dtag=$RELEASE_VERSION -DreleaseVersion=$RELEASE_VERSION -DdevelopmentVersion=$DEVELOPEMENT_VERSION -DpreparationGoals=validate -DcompletionGoals=install -DfailOnDeprecation=false -Darguments="-Dmaven.site.skip=true -Dmaven.site.deploy.skip=true"
      env:
        GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
        RELEASE_VERSION: ${{ inputs.releaseVersion }}
        DEVELOPEMENT_VERSION: ${{ inputs.developementVersion }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_CENTRAL_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        
    - name: Rollback
      if: failure()
      run: mvn release:rollback -B
